### ISSUE TITLE
Sonic won't compile on Go 1.18

### ISSUE THREAD

**Issue by didip** [bytedance/sonic#157]
Error:

```
# github.com/bytedance/sonic/internal/loader
../../../../pkg/mod/github.com/bytedance/sonic@v1.0.0-rc.3/internal/loader/funcdata.go:27:22: undefined: _ModuleData
../../../../pkg/mod/github.com/bytedance/sonic@v1.0.0-rc.3/internal/loader/funcdata.go:30:27: undefined: _ModuleData
../../../../pkg/mod/github.com/bytedance/sonic@v1.0.0-rc.3/internal/loader/funcdata.go:41:6: undefined: _Func
../../../../pkg/mod/github.com/bytedance/sonic@v1.0.0-rc.3/internal/loader/funcdata.go:42:12: undefined: _ModuleData
../../../../pkg/mod/github.com/bytedance/sonic@v1.0.0-rc.3/internal/loader/funcdata.go:53:16: undefined: _ModuleData
../../../../pkg/mod/github.com/bytedance/sonic@v1.0.0-rc.3/internal/loader/funcdata.go:77:26: undefined: _ModuleData
../../../../pkg/mod/github.com/bytedance/sonic@v1.0.0-rc.3/internal/loader/funcdata_invalid.go:23:6: panic("Unsupported Go version. Supported versions are: 1.15, 1.16, 1.17") (no value) used as value
../../../../pkg/mod/github.com/bytedance/sonic@v1.0.0-rc.3/internal/loader/loader.go:44:58: too many arguments in call to registerFunction
	have (string, uintptr, int, int, uintptr, uintptr, uintptr)
	want (string, uintptr, int, int, uintptr)
```

**Comment by chenzhuoyu** [comment]
Go 1.18 is not released yet, we might consider this after it become stable.

**Comment by tong3jie** [comment]
@chenzhuoyu  1.17.3 error too
![image](https://user-images.githubusercontent.com/14191774/148491727-2c3a6f2f-ff2b-4fd0-b8d1-a1692e9699de.png)
