### ISSUE TITLE
Build with Go 1.26 fails: internal/rt/stubs.go: undefined: GoMapIterator

### ISSUE THREAD

**Issue by stefanb** [bytedance/sonic#895]
When trying to build with Go 1.26rc1 the build fails with:
```
# github.com/bytedance/sonic/internal/rt 

/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/bytedance/sonic@v1.14.0/internal/rt/stubs.go:33:22: undefined: GoMapIterator 

/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/bytedance/sonic@v1.14.0/internal/rt/stubs.go:36:54: undefined: GoMapIterator 
```

Same applies also to currently latest release 1.14.2.

See multiple failures downstream:
* https://github.com/Homebrew/homebrew-core/pull/258912

Previous related PRs:
* https://github.com/bytedance/sonic/pull/741
* https://github.com/bytedance/sonic/pull/808
